webApp/passkeeper/service_passwords/routes.py
from Crypto.Random import get_random_bytes
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from datetime import datetime
from flask_wtf.csrf import CSRFError
from passkeeper import db
import bcrypt
from passkeeper.models import Password, User
from passkeeper.service_passwords.forms import PasswordForm, SharePasswordForm
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad, pad
import argon2
import os


service_passwords = Blueprint('service_passwords', __name__)


@service_passwords.errorhandler(CSRFError)
def csrf_error(reason):
    return render_template('csrf_error.html', reason=reason)


@service_passwords.route('/password/new', methods=['GET', 'POST'])
@login_required
def new_password():
    form = PasswordForm()
    if form.validate_on_submit():
        main_key = os.environ.get('PASSWORDS_KEY').encode()
        key = argon2.hash_password_raw(main_key, current_user.salt, hash_len=32, type=argon2.Type.ID)
        iv = get_random_bytes(16)
        aes = AES.new(key, AES.MODE_CBC, iv)
        enc_password = aes.encrypt(pad(str.encode(form.service_password.data), AES.block_size))
        service_pass = Password(service_name=form.service_name.data, service_password=enc_password, iv=iv,
                                owner=current_user)
        db.session.add(service_pass)
        db.session.commit()
        flash('Twoje nowe hasło do serwisu ' + form.service_name.data + ' zostało dodane!', 'success')
        return redirect(url_for('users.my_passwords'))
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('create_password.html', title='Nowe hasło', form=form, legend='Nowe hasło')


@service_passwords.route('/password/<int:password_id>', methods=['GET', 'POST'])
@login_required
def password(password_id):
    pswd = Password.query.get_or_404(password_id)
    if current_user == pswd.owner or current_user in pswd.users_shared:
        main_key = os.environ.get('PASSWORDS_KEY').encode()
        key = argon2.hash_password_raw(main_key, pswd.owner.salt, hash_len=32, type=argon2.Type.ID)
        iv = pswd.iv
        aes = AES.new(key, AES.MODE_CBC, iv)
        decrypted = unpad(aes.decrypt(pswd.service_password), AES.block_size).decode('utf-8')
    else:
        abort(403)
    return render_template('password.html', title=pswd.service_name, password=pswd, decrypted=decrypted)


@service_passwords.route('/password/<int:password_id>/update', methods=['GET', 'POST'])
@login_required
def update_password(password_id):
    pswd = Password.query.get_or_404(password_id)
    if pswd.owner != current_user:
        abort(403)
    form = PasswordForm()
    if form.validate_on_submit():
        pswd.service_name = form.service_name.data
        main_key = os.environ.get('PASSWORDS_KEY').encode()
        key = argon2.hash_password_raw(main_key, current_user.salt, hash_len=32, type=argon2.Type.ID)
        iv = get_random_bytes(16)
        aes = AES.new(key, AES.MODE_CBC, iv)
        pswd.service_password = aes.encrypt(pad(str.encode(form.service_password.data), AES.block_size))
        pswd.date_modified = datetime.now()
        pswd.iv = iv
        db.session.commit()
        flash('Twoje hasło do serwisu ' + form.service_name.data + ' zostało zaktualizowane!', 'success')
        return redirect(url_for('service_passwords.password', password_id=pswd.id))
    elif request.method == 'GET':
        form.service_name.data = pswd.service_name
        main_key = os.environ.get('PASSWORDS_KEY').encode()
        key = argon2.hash_password_raw(main_key, current_user.salt, hash_len=32, type=argon2.Type.ID)
        iv = pswd.iv
        aes = AES.new(key, AES.MODE_CBC, iv)
        decrypted = unpad(aes.decrypt(pswd.service_password), AES.block_size).decode('utf-8')
        form.service_password.data = decrypted
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('create_password.html', title='Zaktualizuj hasło', form=form, legend='Zaktualizuj hasło')


@service_passwords.route('/password/<int:password_id>/delete', methods=['POST'])
@login_required
def delete_password(password_id):
    pswd = Password.query.get_or_404(password_id)
    service_name = pswd.service_name
    if pswd.owner != current_user:
        abort(403)
    db.session.delete(pswd)
    db.session.commit()
    flash('Twoje hasło do serwisu ' + service_name + ' zostało usunięte!', 'success')
    return redirect(url_for('users.my_passwords'))


@service_passwords.route('/password/<int:password_id>/share', methods=['GET', 'POST'])
@login_required
def share_password(password_id):
    pswd = Password.query.get_or_404(password_id)
    if pswd.owner != current_user:
        abort(403)
    form = SharePasswordForm()
    if form.validate_on_submit():
        pepper = os.environ.get("PEPPER").encode()
        if bcrypt.checkpw(form.password.data.encode() + pepper, current_user.password):
            with_user = User.query.filter_by(username=form.username.data).first()
            if with_user is not None:
                if with_user not in pswd.users_shared:
                    pswd.users_shared.append(with_user)
                    db.session.commit()
                    flash('Twoje hasło do serwisu ' + pswd.service_name + ' zostało udostępnione!', 'success')
                    return redirect(url_for('service_passwords.password', password_id=pswd.id))
                else:
                    flash('To hasło już jest udostępnione użytkownikowi o nazwie ' + form.username.data, 'danger')
            else:
                flash('Użytkownik o nazwie ' + form.username.data + ' nie istnieje', 'danger')
        else:
            flash('Niepoprawne hasło', 'danger')
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('share_password.html', title='Udostępnij hasło', form=form)


@service_passwords.route('/password/<int:password_id>/delete/<string:username>', methods=['GET', 'POST'])
@login_required
def delete_with_user_password(password_id, username):
    pswd = Password.query.get_or_404(password_id)
    if pswd.owner != current_user:
        abort(403)
    user = User.query.filter_by(username=username).first()
    pswd.users_shared.remove(user)
    db.session.commit()
    flash('Użytkownik ' + username + ' już nie ma dostępu do hasła serwisu ' + pswd.service_name, 'success')
    return redirect(url_for('users.my_passwords'))

webApp/passkeeper/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_wtf.csrf import CSRFError
from passkeeper import db
from datetime import datetime, timedelta
import bcrypt
from passkeeper.models import User, Password, Attempt
from passkeeper.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm, ChangePasswordForm)
from passkeeper.users.utils import send_reset_email, entropy, send_new_ip_email
import os
import time
import random

users = Blueprint('users', __name__)


@users.errorhandler(CSRFError)
def csrf_error(reason):
    return render_template('csrf_error.html', reason=reason)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.my_passwords'))
    form = RegistrationForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt(15)
        pepper = os.environ.get('PEPPER').encode()
        hashed_password = bcrypt.hashpw(form.password.data.encode() + pepper, salt)
        wait_time = random.uniform(0, 1)
        time.sleep(wait_time)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, salt=salt)
        db.session.add(user)
        db.session.commit()
        flash('Twoje konto zostało utworzone! Możesz się teraz zalogować', 'success')
        return redirect(url_for('users.login'))
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('register.html', title='Zarejestruj', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.my_passwords'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            attempt = Attempt.query.filter_by(user_id=user.id).first()
            if not attempt:
                att = Attempt(user_id=user.id, attempts_left=3)
                db.session.add(att)
                db.session.commit()
                attempt = att
            else:
                if attempt.attempts_left == 0 and attempt.to_date < datetime.now():
                    attempt.attempts_left = 3
                    db.session.commit()
            if attempt.attempts_left > 0:
                pepper = os.environ.get('PEPPER').encode()
                if bcrypt.checkpw(form.password.data.encode() + pepper, user.password):
                    wait_time = random.uniform(0, 1)
                    time.sleep(wait_time)
                    login_user(user)
                    next_page = request.args.get('next')
                    attempt.attempts_left = 3
                    db.session.commit()
                    # send_new_ip_email(user, str(request.environ['REMOTE_ADDR']))
                    # ip = request.remote_addr
                    # flash("Logowanie z adresu " + ip, 'info')
                    return redirect(next_page) if next_page else redirect(url_for('users.my_passwords'))
                else:
                    attempt.attempts_left -= 1
                    db.session.commit()
                    if attempt.attempts_left == 2:
                        flash('Nie udało się zalogować. Sprawdź poprawność emaila i hasła. Pozostały 2 próby.', 'danger')
                    elif attempt.attempts_left == 1:
                        flash('Nie udało się zalogować. Sprawdź poprawność emaila i hasła. Pozostała 1 próba.', 'danger')
                    else:
                        attempt.to_date = datetime.now() + timedelta(hours=24)
                        db.session.commit()
                        flash('Nie udało się zalogować. Twoje konto zostało zablokowane na 24 godziny.', 'danger')
            else:
                flash('Twoje konto jest zablokowane do ' + attempt.to_date.strftime('%d.%m %H:%M') + '.', 'danger')
        else:
            flash('Nie istnieje konto powiązane z podanym emailem.', 'danger')
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('login.html', title='Zaloguj', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.my_passwords'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Twoje konto zostało zaktualizowane!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('account.html', title='Moje konto', form=form)


@users.route('/account/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=current_user.username).first()
        pepper = os.environ.get('PEPPER').encode()
        if user and bcrypt.checkpw(form.old_password.data.encode() + pepper, user.password):
            wait_time = random.uniform(0, 1)
            time.sleep(wait_time)
            entr, extent = entropy(form.confirm_new_password.data)
            hashed_new_password = bcrypt.hashpw(form.confirm_new_password.data.encode() + pepper, user.salt)
            user.password = hashed_new_password
            db.session.commit()
            flash('Twoje hasło zostało zmienione! Entropia hasła: ' + str(round(entr, 2)) + ', stopień: ' + str(round(extent*100, 2)) + '%.', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Nie udało się zmienić hasła. Niepoprawne stare hasło', 'danger')
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('change_password.html', title='Zmień hasło', form=form)


@users.route('/my_passwords')
@login_required
def my_passwords():
    page = request.args.get('page', default=1, type=int)
    passwords = Password.query.filter_by(owner_id=current_user.id)
    received = [p.id for p in current_user.received_passwords]
    re = Password.query.filter(Password.id.in_(received))
    passwords = passwords.union(re).order_by(Password.date_modified.desc()).paginate(page=page, per_page=5)
    return render_template('my_passwords.html', title='Moje hasła', passwords=passwords)


@users.route('/user/<string:username>')
def user_account(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user_account.html', user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.my_passwords'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Na podanego emaila została wysłana wiadomość z dalszymi instrukcjami resetowania hasłą', 'info')
        return redirect(url_for('users.login'))
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('reset_request.html', title='Zresetuj hasło', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.my_passwords'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Niepoprawny lub wygasły token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        pepper = os.environ.get('PEPPER').encode()
        hashed_new_password = bcrypt.hashpw(form.password.data.encode() + pepper, user.salt)
        wait_time = random.uniform(0, 1)
        time.sleep(wait_time)
        user.password = hashed_new_password
        db.session.commit()
        flash('Twoje hasło zostało zmienione! Możesz się teraz zalogować', 'success')
        return redirect(url_for('users.login'))
    else:
        if 'csrf_token' in form.errors:
            flash('Zablokowano próbę wykonania żądania.', 'danger')
    return render_template('reset_token.html', title='Zresetuj hasło', form=form)

webApp/passkeeper/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <h2 class="account-heading text-center">{{ current_user.username }}</h2>
                <p class="text-secondary text-center">{{ current_user.email }}</p>
            </div>
        </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Moje konto</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1 float-right" href="{{ url_for('users.change_password') }}">Zmień hasło</a>
                </div>
            </form>
    </div>
{% endblock content %}

webApp/passkeeper/templates/change_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Zmień hasło</legend>
             <div class="form-group">
                    {{ form.old_password.label(class="form-control-label") }}
                    {% if form.old_password.errors %}
                        {{ form.old_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.old_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.old_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.new_password.label(class="form-control-label") }}
                    {% if form.new_password.errors %}
                        {{ form.new_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.new_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.new_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            <div class="form-group">
                    {{ form.confirm_new_password.label(class="form-control-label") }}
                    {% if form.confirm_new_password.errors %}
                        {{ form.confirm_new_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_new_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_new_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

webApp/passkeeper/templates/csrf_error.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1>Niepoprawny token CSRF</h1>
        <p>Zablokowano wykonanie żądania</p>
    </div>
{% endblock content %}

webApp/passkeeper/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Passkeeper - o aplikacji</h1>
{% endblock content %}

webApp/passkeeper/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>PassKeeper - {{ title }}</title>
    {% else %}
        <title>PassKeeper</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">PassKeeper</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('users.my_passwords') }}">Lista haseł</a>
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('service_passwords.new_password') }}">Nowe hasło</a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Moje konto</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Wyloguj</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Zaloguj</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Zarejestruj</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

webApp/passkeeper/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Zaloguj</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Nie pamiętam hasła</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Nie masz jeszcze konta? <a class="ml-2" href="{{ url_for('users.register') }}">Zarejestruj się teraz</a>
        </small>
    </div>
{% endblock content %}

webApp/passkeeper/templates/my_passwords.html
{% extends "layout.html" %}
{% block content %}
    {% for password in passwords.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="text-muted float-left mr-2">Właściciel: </a>
                    <a class="mr-2" href="{{ url_for('users.user_account', username=password.owner.username) }}">{{ password.owner.username }}</a>
                    <small class="text-muted float-right">Ostatnia modyfikacja: {{ password.date_modified.strftime('%Y-%m-%d %H:%M') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('service_passwords.password', password_id=password.id) }}">{{ password.service_name }}</a></h2>
            </div>
        </article>
    {% endfor %}
    {% for page_num in passwords.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if passwords.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.my_passwords', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.my_passwords', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

webApp/passkeeper/templates/password.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_account', username=password.owner.username) }}">{{ password.owner.username }}</a>
                <small class="text-muted">{{ password.date_modified.strftime('%Y-%m-%d %H:%M') }}</small>
            </div>
            <h2 class="article-title">{{ password.service_name }}</h2>
            <p class="article-content">Hasło: {{ decrypted }}</p>
            <h5 class="article-title">Udostępnione użytkownikom:</h5>
	    <div class="container">
		{% for with_user in password.users_shared %}
		     <div class="row mb-2">
			<div class="col-sm"><li>{{ with_user.username }}</li></div>
			<div class="col-sm">
				{% if password.owner == current_user %}
					<a class="btn btn-danger btn-sm float-right" href="{{ url_for('service_passwords.delete_with_user_password', password_id=password.id, username=with_user.username) }}">Usuń udostępnienie</a>
				{% endif %}
			</div>
			</div>
		{% endfor %}
	    </div>
	    {% if password.owner == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('service_passwords.update_password', password_id=password.id) }}">Zaktualizuj</a>
                    <a class="btn btn-warning btn-sm mt-1 mb-1 ml-1" href="{{ url_for('service_passwords.share_password', password_id=password.id) }}">Udostępnij</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Usuń</button>
                </div>
            {% endif %}
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Usunąć hasło?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
              <form action="{{ url_for('service_passwords.delete_password', password_id=password.id) }}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Usuń">
                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content%}